environment: development

apphost: k8s

label:
  name: AksApi

container:
  name: aspnet3
  pullPolicy: IfNotPresent
  image: aspnet3k8s # How do we link the two?
  tag: v1 # 
  port: 80
  probeDelay: 30

replicas: 3

service:
  port: 8888
  type: ClusterIP